export const categoryItem = [
    {
        id: 1,
        img: 'https://i.ibb.co/yd1FzdT/beer.jpg',
        icon:'https://i.ibb.co/dmv6BLt/icons8-wine-bar-bubbles-32.png',
        cat: 'Bevande',
    },
    {
        id: 2,
        img: 'https://cdn.pixabay.com/photo/2017/03/10/06/20/bruschetta-2131893_1280.jpg',
        icon:'https://i.ibb.co/NNMLCbz/icons8-cashew-bubbles-32.png',
        cat: 'Antipasti',
    },
    {
        id: 3,
        img: 'https://cdn.pixabay.com/photo/2018/02/13/15/05/pasta-3150916_1280.jpg',
        icon:'https://i.ibb.co/HGdYh0f/icons8-dumplings-bubbles-32.png',
        cat: 'Primi',
    },
    {
        id: 4,
        img: 'https://cdn.pixabay.com/photo/2017/02/22/23/19/asian-food-2090938_1280.jpg',
        icon:'https://i.ibb.co/VHNwbkS/icons8-rack-of-lamb-bubbles-32.png',
        cat: 'Secondi',
    },
    {
        id: 5,
        img: 'https://cdn.pixabay.com/photo/2017/10/28/19/07/tiramisu-2897900_1280.jpg',
        icon:'https://i.ibb.co/x8XrpZp/icons8-cherry-cheesecake-bubbles-32.png',
        cat: 'Dessert',
    },
];


export const productList = [
    {
        id: 1,
        cat: 'Bevande',
        title: 'Acqua Naturale',
        img: 'https://i.ibb.co/yd1FzdT/beer.jpg',
        descr:'acqua naturale del fiume stocazzo',
        descrCard: 'acqua naturale da 0.5cL',
        price: '1.00',
    },
    {
        id: 2,
        cat: 'Bevande',
        title:  'Birra',
        img: 'https://i.ibb.co/yd1FzdT/beer.jpg',
        descr:  'Birra da 0.5L in bottiglia',
        descrCard: 'Birra da 0.5L',
        price:  '2.30',
    },
    {
        id: 3,
        cat: 'Bevande',
        title:  'CocaCola',
        img: 'https://i.ibb.co/yd1FzdT/beer.jpg',
        descr:  'CocaCola da 1L in bottiglia',
        descrCard:  'CocaCola da 1L in bottiglia',
        price:  '1.50',
    },
    {
        id: 4,
        cat: 'Primi',
        title:  'Spaghetti',
        img: 'https://cdn.pixabay.com/photo/2018/02/13/15/05/pasta-3150916_1280.jpg',
        descr:  'spaghetti ar sugo',
        descrCard:  'spaghetti • pomodoro',
        price:  '6.50',
    },
    {
        id: 5,
        cat: 'Primi',
        title:  'Spaghetti al ragù',
        img: 'https://cdn.pixabay.com/photo/2018/02/13/15/05/pasta-3150916_1280.jpg',
        descr:  'spaghetti con ragù di carne',
        descrCard:  'spaghetti • ragù carne',
        price:  '7.00',
    },
    {
        id: 6,
        cat: 'Primi',
        title:  'Pennette alla Thevenin',
        img: 'https://cdn.pixabay.com/photo/2018/02/13/15/05/pasta-3150916_1280.jpg',
        descr:  'pennette al pesto',
        descrCard:  'pennette • pesto',
        price:  '8.50',
    },
    {
        id: 7,
        cat: 'Primi',
        title:  'Pennette allo scoglio',
        img: 'https://cdn.pixabay.com/photo/2018/02/13/15/05/pasta-3150916_1280.jpg',
        descr:  'pennette con pesce',
        descrCard:  'pennette • pesce',
        price:  '9.50',
    },
    {
        id: 8,
        cat: 'Secondi',
        title:  'Carne alla griglia',
        img: 'https://i.ibb.co/vZr6Yh5/meal.jpg',
        descr:  'Carne di manzo da 500gr',
        descrCard:  'Carne • manzo • 500gr',
        price:  '12.00',
    },
    {
        id: 9,
        cat: 'Secondi',
        title:  'Salsicce',
        img: 'https://i.ibb.co/vZr6Yh5/meal.jpg',
        descr:  'salsicce con carne di bufalo',
        descrCard:  'salsicce • carne • bufalo',
        price:  '10.00',
    },
    {
        id: 10,
        cat: 'Secondi',
        title:  'Salmone 100gr',
        img: 'https://i.ibb.co/vZr6Yh5/meal.jpg',
        descr:  'salmone con contorno di patate',
        descrCard:  'salmone • patate',
        price:  '12.50',
    },
    {
        id: 11,
        cat: 'Dessert',
        title:  'Tiramisù',
        img: 'https://cdn.pixabay.com/photo/2017/10/28/19/07/tiramisu-2897900_1280.jpg',
        descr:  'Tiramisù • mascarpone • panna • biscotti',
        descrCard:  'Tiramisù',
        price:  '8.50',
    },
    {
        id: 12,
        cat: 'Antipasti',
        title:  'Bruschette',
        img: 'https://cdn.pixabay.com/photo/2017/03/10/06/20/bruschetta-2131893_1280.jpg',
        descr:  'Bruschette con mozzarella e salsiccia',
        descrCard:  'Bruschette ',
        price:  '8.50',
    },
];

export const bestProducts = [
    {
        id: 2,
        img: 'https://i.ibb.co/yd1FzdT/beer.jpg',
        cat: 'Bevande',
        title: 'Birra',
        price:  '2',
        descrCard:  'Birra da 0.5l in bottiglia',
    },
    {
        id: 12,
        img: 'https://cdn.pixabay.com/photo/2017/03/10/06/20/bruschetta-2131893_1280.jpg',
        cat: 'Antipasti',
        title: 'Bruschette',
        price:  '6',
        descrCard:  'Bruschette con mozzarella e salsiccia',
    },
    {
        id: 5,
        img: 'https://cdn.pixabay.com/photo/2018/02/13/15/05/pasta-3150916_1280.jpg',
        cat: 'Primi',
        title: 'spaghetti al ragù',
        price:  '8',
        descrCard: 'spaghetti al ragù di carne',
    },
    {
        id: 8,
        img: 'https://cdn.pixabay.com/photo/2017/02/22/23/19/asian-food-2090938_1280.jpg',
        cat: 'Secondi',
        title: 'Carne alla griglia',
        price:  '12',
        descrCard: 'Carne di manzo da 500gr',
    },
    {
        id: 11,
        img: 'https://cdn.pixabay.com/photo/2017/10/28/19/07/tiramisu-2897900_1280.jpg',
        cat: 'Dessert',
        title: 'Tiramisù',
        price:  '12',
        descrCard: 'Tiramisù con mascarpone e biscotti',
    },
];
